"""initial

Revision ID: 05cc6fe7f761
Revises: 
Create Date: 2025-05-04 19:07:04.189453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '05cc6fe7f761'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('menu_items', 'name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('menu_items', 'code',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('menu_items', 'price',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('menu_items', 'group_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_index('ix_menu_items_name', table_name='menu_items')
    op.create_index(op.f('ix_menu_items_name'), 'menu_items', ['name'], unique=False)
    op.create_foreign_key(None, 'order_items', 'menu_items', ['menu_item_id'], ['id'])
    op.drop_index('order_code', table_name='orders')
    op.create_index(op.f('ix_orders_order_code'), 'orders', ['order_code'], unique=True)
    op.create_foreign_key(None, 'orders', 'staff', ['staff_id'], ['id'])
    op.create_foreign_key(None, 'orders', 'shifts', ['shift_id'], ['id'])
    op.alter_column('staff', 'code',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('staff', 'address',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.String(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('staff', 'address',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('staff', 'code',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_index(op.f('ix_orders_order_code'), table_name='orders')
    op.create_index('order_code', 'orders', ['order_code'], unique=True)
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.drop_index(op.f('ix_menu_items_name'), table_name='menu_items')
    op.create_index('ix_menu_items_name', 'menu_items', ['name'], unique=True)
    op.alter_column('menu_items', 'group_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('menu_items', 'price',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('menu_items', 'code',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('menu_items', 'name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###
