"""Initial migration

Revision ID: bdf24ff56237
Revises: 
Create Date: 2025-05-04 19:50:36.687982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'bdf24ff56237'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Thêm cột total_price vào bảng order_items
    op.add_column('order_items', sa.Column('total_price', sa.Float(), nullable=True))
    
    # Cập nhật giá trị cho cột total_price
    op.execute('UPDATE order_items SET total_price = unit_price * quantity')
    
    # Sửa độ dài cột trong bảng staff
    op.alter_column('staff', 'code',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('staff', 'address',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.String(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('staff', 'address',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('staff', 'code',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
               
    op.drop_column('order_items', 'total_price')
    # ### end Alembic commands ###
